#!/bin/bash

set -e

# Usage prints the help for this command.
usage() {
  echo "Usage:"
  echo "    docker-build command"
  echo ""
  echo "Commands:"
  echo "    build  Build a docker image from this repo and tag it with the git sha and branch"
  echo "    push   Push the built image to the docker registry. \$DOCKER_EMAIL, \$DOCKER_USER, and \$DOCKER_PASS are required"
  exit 1
}

# Build builds the docker image and tags it with the git sha and branch.
build() {
  declare repo="$1" sha="$CIRCLE_SHA1" branch="$CIRCLE_BRANCH" tag="$CIRCLE_TAG"
  docker build --rm=false -t "$repo" .
  docker tag -f "$repo" "${repo}:${tag}"
}

# Push pushes all of the built docker images.
push() {
  declare repo="$1" tag="$CIRCLE_TAG"

  if [ -z "$DOCKER_EMAIL" ] || [ -z "$DOCKER_USER" ] || [ -z "$DOCKER_PASS" ]; then
    usage
  fi

  docker login -e "$DOCKER_EMAIL" -u "$DOCKER_USER" -p "$DOCKER_PASS"
  docker push "$repo:$tag"
}

case "$1" in
  "build")
    build "$REPO"
    ;;
  "push")
    push "$REPO"
    ;;
  *)
    usage
    ;;
esac
