version: '2'

services:
  mariadb01-it:
     image: mysql:5.6
     container_name: mariadb01-it
     hostname: mariadb01-it
     volumes:
       - ./mysql:/var/lib/mysql/
     ports:
       - 3306:3306
     environment:
       - MYSQL_ROOT_PASSWORD=1
       - MYSQL_DATABASE=itshelldb
       - MYSQL_USER=root
       - MYSQL_PASSWORD=1
     
  wordpress-itshellws1:
     image: nightmareze1/zz:v0.0.0.31
     container_name: wordpress-itshellws1
     volumes:
       - ./html:/var/www/html 
       - ./apache2/apache2.conf:/etc/apache2/apache2.conf
       - ./apache2/mods-available/status.conf:/etc/apache2/mods-available/status.conf
     links:
       - mariadb01-it:itshelldb
     ports:
       - "8088:80"
#     logging:
#      driver: "fluentd"
#      options:
#        fluentd-address: localhost:24224
#        tag: wordpress-itshellws1.access

