apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: itshell
  namespace: default
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: itshell
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: itshell
        image: <REPO>/<PROJECT>:<VERSION>
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30 
          timeoutSeconds: 1
        env:
          - name: WORDPRESS_DB_USER
            value: root
          - name: WORDPRESS_DB_PASSWORD
            value: "1"
          - name: WORDPRESS_DB_NAME
            value: itshelldb
          - name: WORDPRESS_DB_HOST
            value: mariadb01-it
        volumeMounts:
          - name: wordpress-1
            mountPath: /var/www/html
      volumes:
        - name: wordpress-1
          persistentVolumeClaim:
           claimName: claim-var-itshell
      imagePullSecrets:
        - name: myregistrykey
